### ISSUE TITLE
Stream does not support writing.

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/OfficeIMO#65]
@rstm-sf  it seems your change for Save has broken some examples

```
System.NotSupportedException
  HResult=0x80131515
  Message=Stream does not support writing.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowNotSupportedException_UnwritableStream()
   at System.IO.FileStream.SetLength(Int64 value)
   at OfficeIMO.Word.WordDocument.Save(String filePath, Boolean openWord) in C:\Support\GitHub\OfficeIMO\OfficeIMO.Word\WordDocument.cs:line 602
   at OfficeIMO.Word.WordDocument.Save(Boolean openWord) in C:\Support\GitHub\OfficeIMO\OfficeIMO.Word\WordDocument.cs:line 633
   at OfficeIMO.Examples.Word.LoadDocuments.LoadWordDocument_Sample1(Boolean openWord) in C:\Support\GitHub\OfficeIMO\OfficeIMO.Examples\Word\LoadDocuments\LoadDocuments.Sample1.cs:line 30
   at OfficeIMO.Examples.Program.Main(String[] args) in C:\Support\GitHub\OfficeIMO\OfficeIMO.Examples\Program.cs:line 76
```

![image](https://user-images.githubusercontent.com/15063294/201218098-3bcb3104-47c3-4f80-b61f-dfc6c3ec1b88.png)

All examples that load documents seem to be affected:

```cs
LoadDocuments.LoadWordDocument_Sample1(false);
LoadDocuments.LoadWordDocument_Sample2(false);
LoadDocuments.LoadWordDocument_Sample3(false);
```

**Comment by PrzemyslawKlys** [comment]
Never mind, the documents were set to read only and that's why it was throwing an error.
